### ISSUE TITLE
Issue Template

### ISSUE THREAD

**Issue by jkross2003** [underworldcode/underworld3-archive#102]
Create and commit issue template

**Comment by jkross2003** [comment]
<img width="651" alt="Screenshot 2022-12-07 at 4 05 26 pm" src="https://user-images.githubusercontent.com/85479525/206093755-8cd0b9e7-aeb2-4943-8f42-ee0ed0cff561.png">

**Comment by lmoresi** [comment]
Can we have an update on this @julesghub ?

**Comment by julesghub** [comment]
I add some issue templates into development:
* Runtime (bug) Issue.
* Feature request issue.
Please review.

**Comment by lmoresi** [comment]
Are we there, can we close this @julesghub ?

**Comment by julesghub** [comment]
Yes https://github.com/underworldcode/underworld3/commit/12d04ab1745cc6ae2d43a299361a21a60a09021d done
