### ISSUE TITLE
Error with a single particle when in parallel 

### ISSUE THREAD

**Issue by bknight1** [underworldcode/underworld3-archive#108]
I'm trying to make passive tracer(s) parallel-safe, however I'm getting an error when only a single particle is used or if a processor/multiple processors do not contain particles. If all processors have a particle then it runs fine.

I've tried updating the cellid on only procs that contain a particle but the script then hangs.

```
(UW) benknight@Bens-MacBook-Pro Working % mpiexec -np 2 python3 PT_test.py
Traceback (most recent call last):
  File "/Users/benknight/Documents/Research/Github/UW3-benchmarks/Working/PT_test.py", line 22, in <module>
    with passiveSwarm.access(passiveSwarm.particle_coordinates):
  File "/Users/benknight/Documents/Research/Github/underworld3/underworld3/swarm.py", line 547, in __exit__
    cellid[:] = self.em_swarm.mesh.get_closest_cells(coords)
  File "/Users/benknight/Documents/Research/Github/underworld3/underworld3/discretisation.py", line 726, in get_closest_cells
    closest_points, dist, found = self._index.find_closest_point(coords)
  File "underworld3/kdtree.pyx", line 115, in underworld3.kdtree.KDTree.find_closest_point
IndexError: Out of bounds on buffer access (axis 0)
```

Here's a basic example to recreate the issue:

```
import underworld3 as uw
import numpy as np

mesh = uw.meshing.StructuredQuadBox(elementRes =(int(32),int(32)),
                                    minCoords=(0.,0.), 
                                    maxCoords=(1.,1.))

### add a tracer
tracer = np.zeros(shape=(1,2))
tracer[:,0] = 0.2
tracer[:,1] = 0.5

passiveSwarm = uw.swarm.Swarm(mesh)

passiveSwarm.dm.finalizeFieldRegister()

passiveSwarm.dm.addNPoints(npoints=len(tracer))

passiveSwarm.dm.setPointCoordinates(tracer)

### causes the issue
with passiveSwarm.access(passiveSwarm.particle_coordinates):
    passiveSwarm.particle_coordinates.data[:] = tracer
```

**Comment by julesghub** [comment]
@bknight1, can you add a conditional operation around the closest_cell. Something like this in swarm.py:547
`if len(coords) > 0: cellid[:] = self.em_swarm.mesh.get_closest_cells(coords)`

So if there are no particles on that proc the get_closest_cell() function doesn't occur.
A bit hacky, but a simple test.

**Comment by bknight1** [comment]
Thanks for the suggestion Julian, I tried it but the script hangs and does not produce an error message. 

If I try accessing the data only on a processor with a particle:
```
if passiveSwarm.dm.getLocalSize() > 0:
    with passiveSwarm.access(passiveSwarm.particle_coordinates):
        passiveSwarm.particle_coordinates.data[:] = tracer
```
 I get a general MPI error message:
```
mpiexec has exited due to process rank 1 with PID 0 on
node dyn-130-194-161-171 exiting improperly. There are three reasons this could occur:
...
```

**Comment by julesghub** [comment]
Yeah, a conditional around the `with` statement will fail because the context handler performs a `mpi.barrier()` at the end of it i believe.
Put the conditional inside the function ie `swarm.py:547` or around `discretisation.py:726`

**Comment by bknight1** [comment]
I've given it a go and seemed to have got it working, hopefully it doesn't introduce further bugs. To be safe, I've created a new branch with the updates as well as the working example.

**Comment by bknight1** [comment]
Actually I might fold this into the viscoplastic branch as it seems to be okay.

**Comment by bknight1** [comment]
Decided to put the updates into the branch we are working on otherwise it would potentially get lost.

**Comment by bknight1** [comment]
Closing for now as it seems to be working
