### ISSUE TITLE
Unable to populate Annulus mesh with swarm using the default params

### ISSUE THREAD

**Issue by bknight1** [underworldcode/underworld3-archive#112]
```
mesh = uw.meshing.Annulus()

swarm = uw.swarm.Swarm(mesh=mesh)
material = uw.swarm.SwarmVariable(
    "M", swarm, num_components=1, proxy_continuous=False, proxy_degree=0)
swarm.populate(fill_param=1)

with swarm.access():
    print(swarm.data)
```

produces NaN values for x and y coords.

changing swarm populate to the following works: 

`swarm.populate(fill_param=1, layout=uw.swarm.SwarmPICLayout.GAUSS)`

**Comment by bknight1** [comment]
Also doesn't work with box meshes

**Comment by lmoresi** [comment]
Probably my bad. 

I noticed that the GAUSS layout for triangles (i.e. 2D) is actually a 4 / 9 point stencil which seems odd and gives a very non-uniform distribution of points.

What about just using the coord points for discontinuous fields of the appropriate order ? These do seem to be in the right place and work in 2D, 3D (don't they, @knepley ?). The DMSwarm code looks pretty dated for this stuff.

**Comment by knepley** [comment]
Yes, that point layout is not tested and might be wrong. We should fix it to use the current quadrature points for DG schemes.

**Comment by lmoresi** [comment]
It's simple for us to switch to these and we'll give it a go / report back !

**Comment by lmoresi** [comment]
The tests are passing. I need to look at the streak-swarm stuff again and then we might be able to check off the viscosity-plastic part of this lengthy branch.

**Comment by bknight1** [comment]
I'd like to get a scaled visco-plastic benchmark working before we do

**Comment by lmoresi** [comment]
The actual issue is resolved. The discussion is rambling. Closing.
