### ISSUE TITLE
saving two vars separately cannot be run in parallel

### ISSUE THREAD

**Issue by YangHaibin1102** [underworldcode/underworld3-archive#115]
The script only dealing with data saving attached below can run in serial but not in parallel. It saves swarm and mesh. If only swarm or mesh is saved, it can run in parallel, but not for two vars to be save simultaneously. 

`import os
import petsc4py
import underworld3 as uw
import numpy as np
import sympy
from mpi4py import MPI 
comm = MPI.COMM_WORLD 

# +
# Parameters that define the notebook
# These can be set when launching the script as
# mpirun python3 scriptname -uw_resolution=0.1 etc 

resolution = 0.02
maxsteps = 10

U0 = 0.3
expt_name = f"NS_benchmark_DFG2d_1_{resolution}"

os.makedirs(".meshes", exist_ok=True)

# +
import pygmsh

# Mesh a 2D pipe with a circular hole

csize = resolution
csize_circle = 0.5 * csize
res = csize_circle

width = 2.2
height = 0.41
radius = 0.05

if uw.mpi.rank == 0:

    # Generate local mesh on boss process

    with pygmsh.geo.Geometry() as geom:

        geom.characteristic_length_max = csize

        inclusion = geom.add_circle(
            (0.2, 0.2, 0.0), radius, make_surface=False, mesh_size=csize_circle
        )
        domain = geom.add_rectangle(
            xmin=0.0,
            ymin=0.0,
            xmax=width,
            ymax=height,
            z=0,
            holes=[inclusion],
            mesh_size=csize,
        )

        geom.add_physical(domain.surface.curve_loop.curves[0], label="bottom")
        geom.add_physical(domain.surface.curve_loop.curves[1], label="right")
        geom.add_physical(domain.surface.curve_loop.curves[2], label="top")
        geom.add_physical(domain.surface.curve_loop.curves[3], label="left")
        geom.add_physical(inclusion.curve_loop.curves, label="inclusion")
        geom.add_physical(domain.surface, label="Elements")

        geom.generate_mesh(dim=2, verbose=False)
        geom.save_geometry(f".meshes/ns_pipe_flow_{resolution}.msh")

pipemesh = uw.discretisation.Mesh(f".meshes/ns_pipe_flow_{resolution}.msh", 
                                  markVertices=True, 
                                  useMultipleTags=True, 
                                  useRegions=True,
                                  qdegree=3)
pipemesh.dm.view()

x = pipemesh.N.x
y = pipemesh.N.y

# relative to the centre of the inclusion
r = sympy.sqrt((x - 0.2) ** 2 + (y - 0.2) ** 2)
th = sympy.atan2(y - 0.2, x - 0.2)

# need a unit_r_vec equivalent

inclusion_rvec = pipemesh.rvec - 1.0 * pipemesh.N.i - 0.5 * pipemesh.N.j
inclusion_unit_rvec = inclusion_rvec / inclusion_rvec.dot(inclusion_rvec)

# Boundary condition as specified in the diagram

Vb = (4.0 * U0 * y * (0.41 - y)) / 0.41**2

# -

v_soln = uw.discretisation.MeshVariable("U", pipemesh, pipemesh.dim, degree=2)
vs_soln = uw.discretisation.MeshVariable("Us", pipemesh, pipemesh.dim, degree=2)
p_soln = uw.discretisation.MeshVariable("P", pipemesh, 1, degree=1)
vorticity = uw.discretisation.MeshVariable("omega", pipemesh, 1, degree=1)
r_inc = uw.discretisation.MeshVariable("R", pipemesh, 1, degree=1)

# +
swarm = uw.swarm.Swarm(mesh=pipemesh, recycle_rate=20)
v_star = uw.swarm.SwarmVariable("Vs", swarm, pipemesh.dim, 
                            proxy_degree=2, proxy_continuous=True)

swarm.populate(fill_param=2)

# + tags=[]
passive_swarm = uw.swarm.Swarm(mesh=pipemesh)
passive_swarm.populate(
    fill_param=3,
)

with passive_swarm.access(passive_swarm.particle_coordinates):
    passive_swarm.particle_coordinates.data[:, 0] /= 2.0 * width
    passive_swarm.particle_coordinates.data[:, 1] = 0.2

hw = 1000.0 / res
with pipemesh.access(r_inc):
    r_inc.data[:, 0] = uw.function.evaluate(r, pipemesh.data, pipemesh.N)

surface_defn = sympy.exp(-(((r_inc.fn - radius) / radius) ** 2) * hw)

with swarm.access(v_star):
    v_star.data[...] = uw.function.evaluate(v_soln.fn, swarm.data)
    

ts = 0
dt_ns = 1.0e-2

for step in range(0, maxsteps):
    delta_t_swarm = 2.0 * 0.01
    delta_t = min(delta_t_swarm, dt_ns)
    phi = min(1.0, delta_t / dt_ns)

    
    with swarm.access(v_star):
        v_star.data[...] = (
            phi * v_soln.rbf_interpolate(swarm.data) 
            # phi * uw.function.evaluate(v_soln.fn, swarm.data)
            + (1.0 - phi) * v_star.data
        )
        
    # update passive swarm
    passive_swarm.advection(v_soln.fn, delta_t, corrector=False)

    npoints = 20
    passive_swarm.dm.addNPoints(npoints)
    
    with passive_swarm.access(passive_swarm.particle_coordinates):
        for i in range(npoints):
            passive_swarm.particle_coordinates.data[
                -1 : -(npoints + 1) : -1, :
            ] = np.array([0.0, 0.195] + 0.01 * np.random.random((npoints, 2)))

    # update integration swarm
    swarm.advection(v_soln.fn, delta_t, corrector=False)

    if uw.mpi.rank == 0:
        print("Timestep {}, dt {}, dt_s {} phi {}".format(ts, delta_t, delta_t_swarm, phi))

    if ts % 2 == 0:
#        nodal_vorticity_from_v.solve()
#         plot_V_mesh(filename="output/{}_step_{}".format(expt_name, ts))
        
        
        savefile = f"output/{expt_name}"
        
        passive_swarm.save(filename=f"{savefile}.passive_swarm.{ts}.h5")
        
        
        pipemesh.write_timestep_xdmf(savefile, 
                                     meshUpdates=True,
                                     meshVars=[p_soln,v_soln,vorticity], 
                                      index=ts)
        
        

        
#         comm.barrier()
        
    if uw.mpi.rank == 0:
        print(f"------", flush=True)

        
    ts += 1`

**Comment by bknight1** [comment]
Not sure if it's to do with the swarm save stuff I added. I've just added in the petsc way of saving the swarm (although I haven't worked out how to read data stored in the pbin file) ee2a532
