### ISSUE TITLE
PyVista & `panel` backend

### ISSUE THREAD

**Issue by julesghub** [underworldcode/underworld3-archive#131]
I'm seeing a lot of this:
`PyVistaDeprecationWarning: `panel` backend is deprecated and is planned for future removal.`

We can switch to 'trame' as the backend, but it requires some new dependencies. Will need to update the documentation and installation instructions.

**Comment by lmoresi** [comment]
trame is great and I have ended up having to switch. 

I seem to have a Jupyter-lab bug in which run-all-cells always crashes as it passes a visualisation cell. If run one cell at a time - no problem.

**Comment by lmoresi** [comment]
We have fixes for this from @gthyagi and the whole thing is a moving target while the pyvista people get themselves organised.
