### ISSUE TITLE
the equation system couldn't  rebuild correctly after mesh deformed

### ISSUE THREAD

**Issue by NengLu** [underworldcode/underworld3-archive#143]
_mesh.deform_mesh_ shows errors below when mesh contains the equation system (e.g. stokes) as the equation system couldn't rebuild correctly.

```
_---> 23 mesh.deform_mesh(new_mesh_coords)

File ~/env_uw3/underworld3/underworld3/discretisation.py:497, in Mesh.deform_mesh(self, new_coords)
    494 self.nuke_coords_and_rebuild()
    496 for eq_system in self._equation_systems_register:
--> 497     eq_system._rebuild_after_mesh_update()
    499 return

File ~/env_uw3/underworld3/underworld3/cython/petsc_generic_snes_solvers.pyx:1917, in underworld3.cython.generic_solvers.SNES_Stokes_SaddlePt._setup_discretisation()

AttributeError: 'SNES_Stokes' object has no attribute 'compiled_extensions'_
```

**Comment by lmoresi** [comment]
You could try stokes._reset() as a more aggressive rebuilding strategy. If that works we can look to see what is not being triggered by the current rebuild.


Sent from my iPhone

On 3 Jan 2024, at 21:52, Neng Lu ***@***.***> wrote:

﻿

mesh.deform_mesh shows errors below when mesh contains the equation system (e.g. stokes) as the equation system couldn't rebuild correctly.

_---> 23 mesh.deform_mesh(new_mesh_coords)

File ~/env_uw3/underworld3/underworld3/discretisation.py:497, in Mesh.deform_mesh(self, new_coords)
    494 self.nuke_coords_and_rebuild()
    496 for eq_system in self._equation_systems_register:
--> 497     eq_system._rebuild_after_mesh_update()
    499 return

File ~/env_uw3/underworld3/underworld3/cython/petsc_generic_snes_solvers.pyx:1917, in underworld3.cython.generic_solvers.SNES_Stokes_SaddlePt._setup_discretisation()

AttributeError: 'SNES_Stokes' object has no attribute 'compiled_extensions'_

**Comment by NengLu** [comment]
It works when resetting the solver system manually as:
```
def build_stokes_solver(mesh,v,p):
    stokes = uw.systems.Stokes(mesh, velocityField=v, pressureField=p)
    stokes.constitutive_model = uw.constitutive_models.ViscousFlowModel
    stokes.bodyforce = sympy.Matrix([0, -1 * ND_gravity * density_fn])
    stokes.constitutive_model.Parameters.shear_viscosity_0 = visc_fn
    stokes.add_dirichlet_bc((0.0,0.0), "Left", (0,))
    stokes.add_dirichlet_bc((0.0,0.0), "Right", (0,))
    stokes.add_dirichlet_bc((0.0,0.0), "Bottom", (0,1))
    
    if uw.mpi.size == 1:
        stokes.petsc_options['pc_type'] = 'lu'
    
    stokes.tolerance = 1.0e-6
    stokes.petsc_options["ksp_rtol"] = 1.0e-6
    stokes.petsc_options["ksp_atol"] = 1.0e-6
    stokes.petsc_options["snes_converged_reason"] = None
    stokes.petsc_options["snes_monitor_short"] = None
    return stokes
build_stokes_solver(mesh,v,p)
```
```
while time < max_time:
    stokes = build_stokes_solver(mesh,v,p)
    stokes.solve(zero_init_guess=False)
    dt_solver = stokes.estimate_dt()

    freesuface = FreeSurfaceProcessor(v,dt)
    new_mesh_coords=freesuface.solve()
    mesh.deform_mesh(new_mesh_coords)
    time += dt
```

**Comment by NengLu** [comment]
See details in the "working" case:
https://github.com/NengLu/underworld3/blob/dev-freesurf/Jupyterbook/Notebooks/Examples-FreeSurface/Ex_TopoRelaxation_FreeSurface.py

Still have two issues in the deformed mesh case:
1. solver rebuild
2. swarm repopulate (tried Ben's pop control method, while not suitable for the deformed mesh case)
![image](https://github.com/underworldcode/underworld3/assets/57476594/a902b7c2-adc1-4e47-8f1b-49d95e57164a)

**Comment by bknight1** [comment]
Nice @NengLu! The repopulate/redistribute won't work for the deformed mesh as it uses the original particle position to repopulate the cells. 

What you could do is create a temporary swarm from the deformed mesh, then only add the particles where needed. 

Alternatively you could make a new swarm and transfer the data from the old swarm to the new one.

**Comment by NengLu** [comment]
Thanks! @bknight1 Very helpful, going to try that!

**Comment by NengLu** [comment]
1.AttributeError showed in `mesh.deform_mesh()`:
The attribute "compiled_extensions" of the equation used in` _setup_discretisation() `(the same as `_rebuild_after_mesh_update() `) is defined in `_setup_pointwise_functions()` which hasn't been initialled.

The easier way here is to force equation reset in `.slover()` by: `stokes.solve(zero_init_guess=False,_force_setup=True)`
Then in the solver, it will reset the discretisation and solver:
```
self._setup_pointwise_functions(verbose)
self._setup_discretisation(verbose)
self._setup_solver(verbose)
```

2.swarm repopulate
Fixed by the method similar to Ben's PopControl.redistribute(), but add particles to the underpopulated_cells from the new swarm build on the deformed mesh.
See details in: https://github.com/NengLu/UW3_FreeSurf/tree/main
