### ISSUE TITLE
issue in accessing local variable 'boundaries' in boundary_integrals branch in parallel

### ISSUE THREAD

**Issue by gthyagi** [underworldcode/underworld3-archive#147]
Hi,

`boundaries` variable only defined in rank = 0.

Note: creating this issue that everyone is aware when using recent container in parallel. this should be quickly fixed. 

```python3
import underworld3 as uw
import underworld3.function as fn
import numpy as np
import sympy

mesh = uw.meshing.StructuredQuadBox()

print('File executed successfully!')
```

Error:
```
Traceback (most recent call last):
  File "/home/565/tg7098/uw3_v0p9_models/test.py", line 6, in <module>
    mesh = uw.meshing.StructuredQuadBox()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/underworld3/meshing.py", line 496, in StructuredQuadBox
    boundaries=boundaries,
               ^^^^^^^^^^
UnboundLocalError: cannot access local variable 'boundaries' where it is not associated with a value
```

**Comment by bknight1** [comment]
Good pick up, the boundaries (and boundary normals) needs to be created on each proc instead of the root proc.

I'll try and fix it up now.

**Comment by lmoresi** [comment]
We can drop the normals from this point on - the rank 0 bug is a good catch !!
Sent from my iPhone

On 17 Jan 2024, at 12:59, Ben Knight ***@***.***> wrote:

﻿

Good pick up, the boundaries (and boundary normals) needs to be created on each proc instead of the root proc.

I'll try and fix it up now.

**Comment by lmoresi** [comment]
I think this is now fixed - @bknight1, can we close this ?

**Comment by bknight1** [comment]
@gthyagi can you close this if it's fixed please
