### ISSUE TITLE
Swarm write_timestep hangs in parallel 

### ISSUE THREAD

**Issue by jcgraciosa** [underworldcode/underworld3-archive#153]
In Gadi, when I attempt to save a swarm as shown below

```python
swarm.write_timestep(filename, "swarm", swarmVars = [], outputPath = outputPath, index=0) 
```

, it hangs when done in parallel.

**Comment by bknight1** [comment]
There's an issue with the parallel implementation. For now, you can use swarm.petsc_save_checkpoint function to save all swarm variables

**Comment by lmoresi** [comment]
``` python
swarm.write_timestep(filename, 
           "swarm", 
           swarmVars = [], 
           outputPath = outputPath, 
           index=0)
```

Have you tried this with the `force_sequential` option, @jcgraciosa ? I am curious why this no longer works as the code is a pretty light wrapper on h5py. Parallel h5 seems to require some special skills to set up which may be missing from the Gadi installation.

**Comment by jcgraciosa** [comment]
I didn't try that option, yet. I'll test it now. 

For the installation of hdf5 and h5py in Gadi, this is the procedure I used: 
```
module load hdf5/1.12.2p

./configure <other PETSc config options> --with-hdf5-dir=$HDF5_DIR

export HDF5_VERSION=1.12.2
HDF5_MPI="ON" pip3 install --no-binary :all: --no-cache-dir h5py 
```

**Comment by jcgraciosa** [comment]
I tried the option with ```force_sequential``` set to True and it works in Gadi (parallel run).

**Comment by lmoresi** [comment]
We've discussed this a few times. `force_sequential` might not be ideal (and maybe it is a bit over-dramatic as an argument) but it's not really our problem to solve. Let's rename the flag to something more neutral such as `exterminate_the_parallel_hdf5_option_exterminate_exterminate_exteeeeeeeerminate=True` and wait for the hdf5 folks or Gadi folks to come up with a fix.
