### ISSUE TITLE
How can freeslip bc be defined for an annulus/sphere without internal boundaries?

### ISSUE THREAD

**Issue by gthyagi** [underworldcode/underworld3-archive#154]
Hi @lmoresi,

I am currently attempting to replicate certain annulus benchmarks. The benchmark with internal boundary loading is performing well. However, the benchmark without internal loading or a non-zero bodyforce term is not yielding the anticipated results. Could you provide guidance on the correct approach for implementing freeslip conditions in the latter case? I am attaching the .py files for debugging purposes.

[Ex_Stokes_Annulus_Benchmark_Kramer_etal.py.txt](https://github.com/underworldcode/underworld3/files/14215734/Ex_Stokes_Annulus_Benchmark_Kramer_etal.py.txt)
[Ex_Stokes_Annulus_Benchmark_Thieulot.py.txt](https://github.com/underworldcode/underworld3/files/14215735/Ex_Stokes_Annulus_Benchmark_Thieulot.py.txt)

Cheers
TG

**Comment by lmoresi** [comment]
I'll take a look at these.

**Comment by lmoresi** [comment]
Boundary conditions are OK - you probably need a penalty closer to 1e6 or 1e7 to constrain the radial velocity but the set up does not look wrong. 

I have errors v. the analytic solution of 10-100% on the Thielot benchmark but I can't check from the notebooks alone. I'll check again when I have access to the papers.

**Comment by gthyagi** [comment]
Even with penalty values ranging from 1e6 to 1e7, I'm still obtaining uw velocity values at approximately 20% of the analytical ones.

**Comment by lmoresi** [comment]
I see that too. There is a fix but I am a bit puzzled by it

Try switching from 
```
Gamma= mesh.Gamma 
```
to 
```
Gamma = meshball.CoordinateSystem.unit_e_0
```
when defining the surface orientation. Does that make a difference for you ?

**Comment by gthyagi** [comment]
Changing the gamma from `mesh.Gamma` to the `unit radial vector` yields velocity values that are roughly 50% of the analytical values.

**Comment by lmoresi** [comment]
Hmmm, I thought it was working when I checked. Now we need to be systematic and figure out what does / does not work.

Can you verify that the Cartesian case (solC) works with your setup.

Can you clarify: is this peak velocity or rms across the domain ?


Sent from my iPhone

On 10 Feb 2024, at 20:33, Thyagarajulu Gollapalli ***@***.***> wrote:

﻿

Changing the gamma from mesh.Gamma to the unit radial vector yields velocity values that are roughly 50% of the analytical values.

**Comment by gthyagi** [comment]
Here are some statistics with my setup.
1. SolCx

`RMS velocity:  1.3088355683348892e-05` `RMS pressure:  0.0032318103770745663`

with following settings:

```python3
stokes.bodyforce = sympy.Matrix(
    [0, -sympy.cos(sympy.pi * x) * sympy.sin(2 * sympy.pi * y)]
)

with mesh.access(v, p):    
    v_I = uw.maths.Integral(mesh, v.sym.dot(v.sym))
    v_rms = np.sqrt(v_I.evaluate()/v.data.shape[0])
    print('RMS velocity: ', v_rms)

    p_I = uw.maths.Integral(mesh, p.sym.dot(p.sym))
    p_rms = np.sqrt(p_I.evaluate()/p.data.shape[0])
    print('RMS pressure: ', p_rms)
```

2. Annulus benchmark (Thieulot)

```python3
# boundary conditions

Gamma = mesh.Gamma
# Gamma = mesh.CoordinateSystem.unit_e_0
stokes.add_natural_bc(2.5e6 * Gamma.dot(v_uw.sym) *  Gamma, "Upper")
stokes.add_natural_bc(2.5e6 * Gamma.dot(v_uw.sym) *  Gamma, "Lower")
```

Case1: `Gamma = unit radial vector`
`Relative error in velocity in the L2 norm:  0.35787879811203727`
`Relative error in pressure in the L2 norm:  0.5991889825108553`

Case2: `Gamma=mesh.Gamma`
`Relative error in velocity in the L2 norm:  0.7448309390575275`
`Relative error in pressure in the L2 norm:  1.217998307418241`

Relative error is calculated using:
<img width="805" alt="Screenshot 2024-02-11 at 10 59 48 am" src="https://github.com/underworldcode/underworld3/assets/44185316/7a3d807a-f5aa-437e-a170-84f17af03de2">

implementation:
```python3
with mesh.access(v_err, p_err, p_ana, v_ana):    
    v_err_I = uw.maths.Integral(mesh, v_err.sym.dot(v_err.sym))
    v_ana_I = uw.maths.Integral(mesh, v_ana.sym.dot(v_ana.sym))
    v_err_l2 = np.sqrt(v_err_I.evaluate())/np.sqrt(v_ana_I.evaluate())
    print('Relative error in velocity in the L2 norm: ', v_err_l2)

    p_err_I = uw.maths.Integral(mesh, p_err.sym.dot(p_err.sym))
    p_ana_I = uw.maths.Integral(mesh, p_ana.sym.dot(p_ana.sym))
    p_err_l2 = np.sqrt(p_err_I.evaluate())/np.sqrt(p_ana_I.evaluate())
    print('Relative error in pressure in the L2 norm: ', p_err_l2)
```

When I set `Gamma=mesh.Gamma`, the relative velocity error is twice as much as in case1. This suggests that the velocity across the entire domain decreases by half.

**Comment by lmoresi** [comment]
Interesting. When I run this for SolCx, I find the solutions match within the tolerance value everywhere in the domain if I use the analytic normals. If I use mesh.Gamma, it's a bit of a mess and I can see quite large errors.

I'll need to look to see if the compiler is getting the normals matched up properly.  

But, @gthyagi, can you confirm - you can't get SolCx to work even using analytic normals ?

**Comment by gthyagi** [comment]
where are analytic normals and how to get them?

**Comment by gthyagi** [comment]
@lmoresi I tried running SolCx script with your recent changes. I think `stokes._reset()` is not working as expected.
If I run SolCx with following bc conditions:
Case1:
```python3
stokes.add_dirichlet_bc((sympy.oo, 0.0), "Top")
stokes.add_dirichlet_bc((sympy.oo,0.0), "Bottom")
stokes.add_dirichlet_bc((0.0,sympy.oo), "Left")
stokes.add_dirichlet_bc((0.0,sympy.oo), "Right")
```

Case2:
```python3
stokes.add_natural_bc([0.0,1e5*v.sym[1]], "Top") 
stokes.add_dirichlet_bc((sympy.oo,0.0), "Bottom")
stokes.add_dirichlet_bc((0.0,sympy.oo), "Left")
stokes.add_dirichlet_bc((0.0,sympy.oo), "Right")
```

Case3:
```python3
Gamma = mesh.Gamma
stokes.add_natural_bc(2.5e6 * Gamma.dot(v.sym) *  Gamma, "Top")
stokes.add_natural_bc(2.5e6 * Gamma.dot(v.sym) *  Gamma, "Bottom")
stokes.add_natural_bc(2.5e6 * Gamma.dot(v.sym) *  Gamma, "Left")
stokes.add_natural_bc(2.5e6 * Gamma.dot(v.sym) *  Gamma, "Right")
```

In all cases, solution matches the tolerance value.

**Comment by gthyagi** [comment]
We have working freeslip boundary condition in both cases (i.e., with/without internal boundary)
