### ISSUE TITLE
Projecting zero vector

### ISSUE THREAD

**Issue by gthyagi** [underworldcode/underworld3-archive#157]
Hi @lmoresi,

What is happening here? After the projection solve, `norm_v` contain zeros. I am getting nan values in the `norm_v` because of normalization.

https://github.com/underworldcode/underworld3/blob/61835dd230206e13dd2e7e274b56d75779945db9/Jupyterbook/Notebooks/Examples-Stokes_Kernels/Ex_Stokes_Annulus_Kernels.py#L75C1-L89C89

**Comment by lmoresi** [comment]
I may need to do this on a fresh checkout to figure out why it doesn't work. 

There are no surface integral tests at the moment and that might be worth fixing so I don't check in things that fail. 

L

**Comment by lmoresi** [comment]
I can't reproduce this problem at the moment. Can somebody else check. 

Is it Linux / Mac. Parallel or serial ?

**Comment by gthyagi** [comment]
I am still using boundary_integrals branch installation to run your recent scripts. I observed the issue on Mac in serial.

**Comment by lmoresi** [comment]
I guess it would be worth trying the current development branch.

**Comment by lmoresi** [comment]
@gthyagi - can review this to let me know if it is still a live issue. Discussion the other day suggested not.

**Comment by gthyagi** [comment]
If you use the latest development branch, you won't encounter this issue.
