### ISSUE TITLE
Advection-diffusion convergence issue

### ISSUE THREAD

**Issue by bknight1** [underworldcode/underworld3-archive#161]
With increasing resolution the error is not showing a convergence order:
![AdvDiff_HP_convergence](https://github.com/underworldcode/underworld3/assets/55677727/f3c22513-b393-4939-9e02-bca3964b8ee0)

The errors are concentrated at the diffusive boundary:
unknown (T) degree comparison:
![Hot_pipe_l1_deg_comparison](https://github.com/underworldcode/underworld3/assets/55677727/9e8d4cd9-a421-4d55-b694-209077524fa1)

diffusivity (D) value comparison:
![Hot_pipe_l1_D_comparison](https://github.com/underworldcode/underworld3/assets/55677727/7c0e2622-6c7a-4d86-90da-1961e16504e2)

To test any updates, the script to check convergence is found [here](https://github.com/underworld-community/UW3_benchmarks_paper/blob/main/Scripts/Run_convergence_AdvDiff.ipynb)

**Comment by lmoresi** [comment]
I had a look at this. I think it is unrealistic to start with a case which has an infinite gradient. I have an example notebook that looks at advection starting from a finite time and looking at the change over time and with advection. I'll upload and you can review.

**Comment by bknight1** [comment]
Keen to have a look!

**Comment by lmoresi** [comment]
@bknight1 Take a look at Jupyterbook/Notebooks/Examples-Convection/Ex_AdvectionDiffusion_1dBlock.py.

I'm careful to start from a finite time after the step-function initial condition is applied so that it can be represented reasonably well by the mesh (maybe less so for the simplex example shown). Move it / diffuse it and compare before the analytic solution becomes invalid.

**Comment by bknight1** [comment]
Makes sense! I'll update the script and see how it performs

**Comment by lmoresi** [comment]
@bknight1 - is this still live with the replacement for the test and the recent debugging ?

**Comment by bknight1** [comment]
Last time I run it the convergence looked a bit better:
[AdvDiff-HP_setup&results.pdf](https://github.com/user-attachments/files/16811017/AdvDiff-HP_setup.results.pdf)

Re-running it now to see if the updates make a difference (updated my install to development last night)

**Comment by bknight1** [comment]
These are the results after the update:

[AdvDiff_convergence_tol=1e-06_new.pdf](https://github.com/user-attachments/files/16811059/AdvDiff_convergence_tol.1e-06_new.pdf)

Which appears to be worse...

**Comment by bknight1** [comment]
Think this has been solved, so closing for now
