### ISSUE TITLE
DMSwarm and the shadow space — is this implemented and is it what we need.

### ISSUE THREAD

**Issue by julesghub** [underworldcode/underworld3-archive#2]

**Comment by knepley** [comment]
What's the shadow space?

**Comment by rbeucher** [comment]
I guess the question is how parallelism Is handled by DMswarm?

**Comment by knepley** [comment]
Each particle is a struct that you create by registration at the start of the program. You attach the particles to something which supports a DMLocate() method, locating the cell which a particle inhabits, perhaps on a different process. DMSwarmMigrate() communicates particles which should live on other processes. There is an example in SNES ex64.

**Comment by rbeucher** [comment]
Thanks @knepley. I'm going to have a look
