### ISSUE TITLE
What mesh formats are currently supported by PETSc for reading?

### ISSUE THREAD

**Issue by gthyagi** [underworldcode/underworld3-archive#209]
Hi @knepley,

What mesh formats, other than Gmsh and Exodus, can PETSc currently read? Is there any documentation available for this?

Thanks.

**Comment by lmoresi** [comment]
Thyagi,

While you are waiting for the definitive response from Matt, have a look at the DMPLEX documentation [here](https://petsc.org/release/manualpages/DMPlex/) and, particularly, all of the DMPLEXcreate_____ functions. That should give you the broad sense of what is possible. Matt can tell you how well each one works.

**Comment by gthyagi** [comment]
Following the Petsc4py example, I was able to create dmplex from .mesh file (medit format).
