### ISSUE TITLE
Trying to run this native

### ISSUE THREAD

**Issue by lmoresi** [underworldcode/underworld3-archive#22]
On MacOS - which looks quite promising (see environment.yml) but:

```
-
RuntimeError                              Traceback (most recent call last)
<ipython-input-6-d3c989ee9763> in <module>
      1 # Solve time
----> 2 poisson.solve()

~/+Codes/underworld3/underworld3/poisson.pyx in underworld3.poisson.Poisson.solve()

~/+Codes/underworld3/underworld3/poisson.pyx in underworld3.poisson.Poisson._setup_terms()

~/+Codes/underworld3/underworld3/_jitextension.cpython-38-darwin.so in underworld3._jitextension.getext()

~/+Codes/underworld3/underworld3/_jitextension.cpython-38-darwin.so in underworld3._jitextension._createext()

RuntimeError: Extension module does not appear to have been created.

```

**Comment by jmansour** [comment]
UW3 creates the extension files within folders named `fn_ptr_ext_iudtyq` (for example). These are created within your system's temp directory (check the `TMPDIR` environment variable). If you jump in there and run `python3 setup.py build_ext --inplace` you should see exactly why it failed. 

If I can find the power supply for my Macbook i'll have a look myself!

**Comment by lmoresi** [comment]
I run `python3 setup.py build_ext —inplace` first in the main uw3 directory as in the readme. That runs without error but produces nothing in the $TMPDIR (which is set, by the way, and the directory is in use by other apps)


On 4 Feb 2021, at 6:09 pm, John Mansour <notifications@github.com<mailto:notifications@github.com>> wrote:



UW3 creates the extension files within folders named fn_ptr_ext_iudtyq (for example). These are created within your system's temp directory (check the TMPDIR environment variable). If you jump in there and run python3 setup.py build_ext --inplace you should see exactly why it failed.

If I can find the power supply for my Macbook i'll have a look myself!

**Comment by jmansour** [comment]
The $TMPDIR is only used at runtime. That’s where the just in time modules
are created.

**Comment by jmansour** [comment]
So for example, **after** you encounter the message you posted above, run

```shell
$ cd ${TMDIR}/fn_ptr_ext_iudtyq   # yours will have a different random string of course
$ python3 setup.py build_ext --inplace
```

and report back.
