### ISSUE TITLE
Command-Line Arguments Not Recognized by PETSc.Options/uw.options

### ISSUE THREAD

**Issue by gthyagi** [underworldcode/underworld3-archive#232]
I'm encountering an issue where the command-line arguments passed to the script are not being recognized by PETSc.Options. Specifically, when running the script with `python3 Example.py --case case4`, the provided argument is not recognized. This is not getting updated 
```python
options = PETSc.Options() 
case = options.getString('case', default='case1') # uw.options.getString('case', default='case1')
```

**Comment by bknight1** [comment]
Had the same issue (#210) just remove the PETSc import. UW handles the options now, no need to import PETSc

**Comment by gthyagi** [comment]
I initially tried using `uw.options`, but it didn't work. I then switched to using `PETSc.Options`, but that didn't resolve the issue either.

**Comment by bknight1** [comment]
This should work:

```
import underworld3 as uw

res  = uw.options.getInt("res")

print(f'res = {res}', flush=True)

```

from the command line:

`python3 test.py -uw_res 5`

should print 'res = 5' in terminal.

You may be missing the  -uw_ prefix?

**Comment by bknight1** [comment]
You have to remove/not import `from petsc4py import PETSc` otherwise it won't work

**Comment by bknight1** [comment]
I'd also remove the default value, so it produces an error and stops the script from running

**Comment by gthyagi** [comment]
> This should work:
> 
> ```
> import underworld3 as uw
> 
> res  = uw.options.getInt("res")
> 
> print(f'res = {res}', flush=True)
> ```
> 
> from the command line:
> 
> `python3 test.py -uw_res 5`
> 
> should print 'res = 5' in terminal.
> 
> You may be missing the -uw_ prefix?

Thanks @bknight1. This method works, but I'm planning to create a single `.py` file that can run both as a notebook and on NCI. If I can't set a default value, I may need to create two separate `.py` files.

**Comment by gthyagi** [comment]
`You may be missing the -uw_ prefix?`
yeah, you are correct. Adding `-uw_` fixes the issue.
Also, I did set `default` value and ran in parallel on mac. It worked. Hopefully it works without any error on NCI too.
Thanks.
