### ISSUE TITLE
Help setting up a two-component coupled system

### ISSUE THREAD

**Issue by bknight1** [underworldcode/underworld3-archive#250]
Hi team,

I'm trying to set up a two-component system as follows:

$$
\frac{\partial C_{\text{A}}}{\partial t} = \nabla \cdot \left( D_{\text{AA}} \nabla C_{\text{A}} + D_{\text{AB}} \nabla C_{\text{B}} \right) 
$$

$$
\frac{\partial C_{\text{B}}}{\partial t} = \nabla \cdot \left( D_{\text{BB}} \nabla C_{\text{B}} + D_{\text{BA}} \nabla C_{\text{A}} \right)
$$

Similar to what is outlined [in eq 2 here](https://citeseerx.ist.psu.edu/document?repid=rep1&type=pdf&doi=973b9a24a4dac26a8631800752cc2dd8b0676551).

I have a sympy matrix for the flux (F1) and dC/dt (F0) terms, which are (2,2) and (2, 1) in shape, respectively.

@julesghub suggested using the _Vector_Projection_ solver, but I can't modify the F1 term to reflect my flux term due to how [F1 is constructed](https://github.com/underworldcode/underworld3/blob/a285eefe9171c7c1b093b49556901e4ebcbcef94/src/underworld3/systems/solvers.py#L993).

Are there any other solvers I can use? I can't use the Poisson solver as it expects scalar F0 and F1 terms.

Cheers

**Comment by lmoresi** [comment]
I did not have problems with the advection-diffusion solver with zero velocity field, though it does have extra baggage in the solver that could be stripped out. Would it be OK to split the coupling terms that way ?

**Comment by bknight1** [comment]
Closing this as I've managed to make a coupled system using two diffusion solvers that matches benchmark values (attached). 

![benchmark_comp](https://github.com/user-attachments/assets/863e8bf3-f545-48f7-aed2-1d862712684d)
