### ISSUE TITLE
Material handling in UW3

### ISSUE THREAD

**Issue by jmansour** [underworldcode/underworld3-archive#27]
From #25 

> However Piecewise mightn't be the best option for other reasons. As discussed on Friday, a smooth alternative might give better mathematical behaviour. But a further and more critical issue with the Piecewise approach results due to the fact that the materialVariable is interpolated to determine which clause to use. This is fine when there's only two materials, but when there's more, the interface between two materials might result in a third material spuriously appearing. For example, if we have material indexes {1,2,3}, at the interface between materials {1} and {3}, the interpolated result might yield material {2}. So a mask approach is really the only correct way forward here I believe.

Discuss.

**Comment by lmoresi** [comment]
See the indexSwarm ... we all want to wear the Mansour masks these days.
