### ISSUE TITLE
swarm.populate:  shape mismatch between variables cells and invalid in swarm.mesh.get_closest_local_cells()

### ISSUE THREAD

**Issue by jcgraciosa** [underworldcode/underworld3-archive#273]
PETSc/petsc4py version: 3.22.2
Underworld3 branch: development (commit 53dbf6d)
Python version: 3.12.7

```swarm.populate()``` contains the following lines: 

```
newp_coords0 = self.mesh._get_coords_for_basis(fill_param, continuous=False)
newp_cells0 = self.mesh.get_closest_local_cells(newp_coords0)
```

When executing ```self.mesh.get_closest_local_cells(newp_coords0)```, the following error occurs: "IndexError: boolean index did not match indexed array along axis 1"

To replicate the error: 

```
import underworld3 as uw
from underworld3.meshing import UnstructuredSimplexBox

mesh = UnstructuredSimplexBox(
    minCoords=(0.0, 0.0),
    maxCoords=(1.0, 1.0),
    cellSize=1.0 / 8.0,
)

fill_param = 3
s_soln = uw.discretisation.MeshVariable("T", mesh, 1, degree=2)
swarm = uw.swarm.Swarm(mesh=mesh)
swarm.populate(fill_param=fill_aram)
```

We can investigate the error from ```mesh.get_closest_local_cells()``` with:

```
newp_coords0 = mesh._get_coords_for_basis(fill_param, continuous=False) # called inside swarm.populate()
min_size, radii, centroids, search_lengths = mesh._get_mesh_sizes() # called in mesh.nuke_coords_and_rebuild()

# The following are called in mesh.get_closest_local_cells()
closest_points, dist, found = mesh._index.find_closest_point(newp_coords0) 
cells = mesh._indexMap[closest_points]
print(cells.shape) # this will result to shape of (1620, 1)

invalid = (
            dist > 0.1 * radii[cells] ** 2  # 2.5 * self._search_lengths[cells]
)
print(invalid.shape) # this will result to shape of (1620, 1620)
cells[invalid] = -1 # cause of error
```

**Comment by jcgraciosa** [comment]
@NengLu has volunteered to look into this since it's adjacent to his issues. 
I can't change the assignee to him so just commenting for now.

**Comment by NengLu** [comment]
Hi JC,
Sorry for that I can not reproduce the error on my system.
(Python3.12.7 PETSC3.22.2 on Ubuntu24.04)
```
newp_coords0 = mesh._get_coords_for_basis(fill_param, continuous=False) # called inside swarm.populate()
min_size, radii, centroids, search_lengths = mesh._get_mesh_sizes() # called in mesh.nuke_coords_and_rebuild()

# The following are called in mesh.get_closest_local_cells()
closest_points, dist, found = mesh._index.find_closest_point(newp_coords0) 
cells = mesh._indexMap[closest_points]
print(cells.shape)  

invalid = (
            dist > 0.1 * radii[cells] ** 2  # 2.5 * self._search_lengths[cells]
)
print(invalid.shape)  
cells[invalid] = -1  
```
The output of the above codes is:
```
(1620,)
(1620,)
```

**Comment by gthyagi** [comment]
Even on macOS, I don't encounter this error with PETSc 3.22.2, Python 3.12.5, and OpenMPI 4.1.6.

**Comment by jcgraciosa** [comment]
Thanks for trying to replicate @gthyagi and @NengLu! :) 

I found that the issue was caused by installing the development branch of the latest petsc4py versions.
In it, ```<swarm_name>.getField("DMSwarm_cellid")``` returns an array of shape ```(X, 1)``` instead of ```(X, )```.

Apologies for not realizing this sooner! Closing this issue.
