### ISSUE TITLE
Errors in interpolation of swarm variable on mesh

### ISSUE THREAD

**Issue by dansand** [underworldcode/underworld3-archive#28]
This error shows up when trying to interpolate some functions from swarm to mesh. These should be able to be reproduced from the stokes-RT example. The density is binary:

```
density = Piecewise( ( 0., Abs(matSwarmVar.fn - lightIndex)<0.5 ),
                     ( 1., Abs(matSwarmVar.fn - denseIndex)<0.5 ),
                     ( 0.,                                True ) )

```
Then try to eveluate on the mesh:

```
uw.function.evaluate(density, mesh.data)
```

In the notebook, I see the following:

```
RuntimeError: Error encountered when trying to interpolate mesh variable.
Interpolation location is possibly outside the domain.
```
In the terminal, the following:

```
]PETSC ERROR: --------------------- Error Message --------------------------------------------------------------
[0]PETSC ERROR: Petsc has generated inconsistent data
[0]PETSC ERROR: Point 1055: 0.9142 0.96875 0. not located in mesh
[0]PETSC ERROR: See https://www.mcs.anl.gov/petsc/documentation/faq.html for trouble shooting.
[0]PETSC ERROR: Petsc Development GIT revision: v3.14.5-711-g91d58987f3  GIT Date: 2021-03-03 16:36:40 -0600
[0]PETSC ERROR: Unknown Name on a  named 0bf297c98414 by Unknown Thu Oct  7 10:40:20 2021
[0]PETSC ERROR: Configure options --with-debugging=1 --prefix=/usr/local --with-petsc4py=1 --with-zlib=1 --download-mumps=1 --download-parmetis=1 --download-metis=1 --download-scalapack=1 --useThreads=0 --with-shared-libraries --with-cxx-dialect=C++11 --download-hdf5=https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-1.10.6/src/hdf5-1.10.6.tar.gz --with-make-np=8 --download-ctetgen --download-eigen --download-triangle
[0]PETSC ERROR: #1 DMInterpolationSetUp_UW() line 108 in underworld3/function/petsc_tools.c

```

Following up on this part of the error message, **Point 1055: 0.9142 0.96875 0. not located in mesh**, it seems that that 1055 is a reference to a node index in the mesh:

```
mesh.data[1055]
array([ 0.9142 ,  0.96875])
```

**Comment by jmansour** [comment]
I assume that point is actually inside the mesh?

**Comment by knepley** [comment]
Is it possible for me to run it? I have just upgraded DMLocatePoints(), and maybe the update obviates the problem.

**Comment by dansand** [comment]
@jmansour. In this example, the function density is based on the swarm (using Piecewise), i did wonder if maybe some of the swarm particles were outside the mesh, but it doesn't seem to be the case (I've checked that no points lie outside or on the mesh boundary). 

It's a unit-square mesh, so node [ 0.9142 ,  0.96875] is inside.

**Comment by jmansour** [comment]
@dansand I don't think the particles should come in to this, as effectively they are out of the picture for the interpolation (but I'll double check).  Also, I don't believe the `Piecewise()` operation should matter, but I'd be interested to know if it fails with `uw.function.evaluate(matSwarmVar.fn, mesh.data)`.

@knepley yes certainly. Let me just confirm compat against the bleeding edge `PETSc`.  @dansand can you post an abridged script?

**Comment by dansand** [comment]
@jmansour - I'll post in the script in a bit. 

Just confirming that the interpolation does work of you use the swarm coords, rather than mesh:

```
with swarm.access(swarm.particle_coordinates):
    out = uw.function.evaluate(density, swarm.particle_coordinates.data)
```

Also works for general point evaluation:

```
uw.function.evaluate(density, np.array([[0.9, 0.9],
                                        [0.1, 0.1]]))
```

array([1., 0.])

And seems to work for direct point evaluation outside the mesh:

```
#evaluate some points that are outside the mesh
uw.function.evaluate(density, np.array([[1.9, 1.9],
                                        [0.1, 0.1]]))
```

**Comment by dansand** [comment]
Simple example here:

https://github.com/dansand/issues/blob/master/uw3_issues/swarm_mesh_eval_test.py

**Comment by lmoresi** [comment]
Probably working. function.evaluate is a bit sensitive but less so than when this issue was opened.
