### ISSUE TITLE
XDMF/hdf5 output -separate mesh and data

### ISSUE THREAD

**Issue by dansand** [underworldcode/underworld3-archive#30]
It would be useful to replicate UW2 capability where we can write a mesh file (h5) and then at subsequent timesteps write mesh variables into the same h5 mesh file. This may already be possible through functionality provided in `petsc_gen_xdmf`, but needs demonstration / testing.

**Comment by lmoresi** [comment]
Ongoing, but we have many ways to dump information that are more reminiscent of the uw2 workflow
