### ISSUE TITLE
velocity evaluate error

### ISSUE THREAD

**Issue by dansand** [underworldcode/underworld3-archive#32]
The following error message occurs (at some resolutions), in the subduction model I've being setting up, which can be found here https://github.com/dansand/uw3_models/blob/main/slabsubduction.ipynb. This was generated with the latest changes to master (566b947)

```python

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-166-c06b8ae04b7c> in <module>
     14     dt = stokes.dt()
     15     with swarm.access():
---> 16         vel_on_particles = uw.function.evaluate(stokes.u.fn,swarm.particle_coordinates.data)
     17 
     18     with swarm.access(swarm.particle_coordinates):

/tmp/uw3/underworld3/function/_function.pyx in underworld3.function._function.evaluate()

/tmp/uw3/underworld3/function/_function.pyx in underworld3.function._function.evaluate.get_var_fns()

/tmp/uw3/underworld3/function/_function.pyx in underworld3.function._function.evaluate.get_var_fns()

/tmp/uw3/underworld3/function/_function.pyx in underworld3.function._function.evaluate.get_var_fns()

AttributeError: 'NoneType' object has no attribute 'mesh'

```

**Comment by jmansour** [comment]
I believe this is possibly related to #28. I've encountered the same message at some point, but the underlying issue was the same as (or similar to) #28.  

Still investigating.

**Comment by dansand** [comment]
Same error occurs when evaluating at points that are definitely inside the mesh, i.e:

```
uw.function.evaluate(stokes.u.fn, np.array([[0.5, 0.5],[0.75, 0.75]]))
```

**Comment by dansand** [comment]
Update -  this problem is not occurring consistently (it seems to go away, then reappear). I don't think it has any direct relationship to changing model resolution as I mentioned in the first ticket.

**Comment by jmansour** [comment]
This exact call pattern is used for the existing RT model, and i've never encountered this issue for that model. So must be something else at play.

I'll have a look at some point this week, but for now I have a mountain of induction documents to read! Fun times.

**Comment by lmoresi** [comment]
Not seeing this problem any more. The code has changed quite a bit and recurrences of the issue are probably coincidental.
 
Closing.
