### ISSUE TITLE
Relax .access() context management for system vars

### ISSUE THREAD

**Issue by julesghub** [underworldcode/underworld3-archive#38]
Mesh and mesh vars should be able to be added after one has called `access()`.
The private variable vector and public aux vector should make this possible.

Once a meshvar is added or deleted the system vector should just be resized and repopulated.

**Comment by julesghub** [comment]
@jmansour please add info on this idea

**Comment by lmoresi** [comment]
I second this one !  Unless it is very difficult to fix, the issue is especially bad in a notebook where a second build of the solver object will crash because the variables already exist (should at least check and re-use).

**Comment by lmoresi** [comment]
1) The secondary issue I raised here is fixed: variables being redefined are now ignored and the original is retained. 
2) We should live with the PETSc data management model and, if people complain, we pass them up the chain.
