### ISSUE TITLE
Sign error in poisson RHS term ?

### ISSUE THREAD

**Issue by lmoresi** [underworldcode/underworld3-archive#42]
I think the source term in the steady-state diffusion problem has a sign reversed. Anyone else noticed this ?

**Comment by lmoresi** [comment]
I mean, it's easy enough to fix if that's all that's the matter, but it's probably more than just adding a minus sign, everything being a sympy function and all that.

**Comment by jmansour** [comment]
Yep, I believe you're correct, and I've implemented it with sign reversed. The test I was using passes, but that's because the source I used for the test had the sign reversed. In any case, my bad, I'll fix. 
The attribute should probably also be `Poisson.f` not `Poisson.h`.

**Comment by lmoresi** [comment]
Thanks John.

Agreed on nomenclature.

L
