### ISSUE TITLE
Population control: projection from swarm to mesh using PetscFE

### ISSUE THREAD

**Issue by rbeucher** [underworldcode/underworld3-archive#57]
I am opening this thread for discussion about implementing population control in UW3

This refers to PR #56 by @lmoresi 

Population control. In particular, the projection from swarm to mesh becomes less and less accurate for NS even though it remains stable. Need to re-populate the swarm near to stagnation points (and prune elsewhere, though this is an efficiency question not an accuracy one). This is the "benchmark" we want to run and there is a lot of additional diffusion because the particles are patchy in the vortex train.

![155657578-cdeea8c6-a582-4043-b777-86d531b0d3d1](https://user-images.githubusercontent.com/3680918/155904760-fcb24c8d-3492-452b-8b06-5daf733b7a8f.png)

**Comment by lmoresi** [comment]
We have a swarm cycling approach implemented. The strategy is to reset a subset of the swarm at each step and it has the effect of creating a streak-swarm along a flow-line. 

Mostly this is a good choice. Particle properties are re-meshed using an rbf interpolation. Some random fluctuations ensure no exactly coincident particles (breaks rbf).
