### ISSUE TITLE
broken visualisation in uw3 & tmp file question

### ISSUE THREAD

**Issue by YangHaibin1102** [underworldcode/underworld3-archive#65]
![image](https://user-images.githubusercontent.com/29653865/162133638-ddc85db7-94a7-448a-9db9-3187fe7914cd.png)

Hi Romain and Louis,

Can you check this visualisation issue in UW3? 

If there are no vis funciton, it will be hard for me to continue other tests.

Cheers,

Haibin

**Comment by lmoresi** [comment]
This is a breaking change that was made by Romain to eliminate some of the  more complicated dependencies.

The new version looks like this. I haven't got around to fixing all the 
notebooks, so please feel free to help out and issue a pull request, Haibin !

```
    mesh.vtk("tmp_mesh.vtk")
    pvmesh = pv.read("tmp_mesh.vtk")

```

@rbeucher, should we wrap these two lines to restore the pyvista function, or provide a better temp file manager for uw ?

**Comment by rbeucher** [comment]
@YangHaibin1102, please use:

```
    mesh.vtk("tmp_mesh.vtk")
    pvmesh = pv.read("tmp_mesh.vtk")
```

**Comment by lmoresi** [comment]
I think we should offer a way to make named tmp files in uw so that we don't have the possibility of race conditions between two codes utilising the same file name which is exactly how things are at the moment with this proposed fix !

I shall leave this open until then.

**Comment by rbeucher** [comment]
Agree. For now it's just a quick and dirty solution.

**Comment by lmoresi** [comment]
Probably close this. We can now read mesh data to new (different) meshes and not have to worry about the details of what we originally saved. Visualisation examples in the repo show how to do this. pyvista can be quite useful as a scriptable post-processing engine in place of paraview.
