### ISSUE TITLE
Boundary condition on non-existent label leads to crash

### ISSUE THREAD

**Issue by lmoresi** [underworldcode/underworld3-archive#82]
This should be intercepted and handled elegantly.

(Particularly since we have English / Australia spellings)

L

**Comment by knepley** [comment]
Is this in Underworld or PETSc?

**Comment by lmoresi** [comment]
I think this is underworld or petsc4py as it is a kernel error in a notebook where it ought to be an exception in python.

**Comment by lmoresi** [comment]
This results from the failure to check if a label exists before querying it. We can fix that by testing (and now we do), but it's a bit annoying. 

Annoying because the pattern feels wrong - it means that there is a valid python object in petsc4py but there is a segmentation fault if the object is accessed.
