### ISSUE TITLE
Stokes sinker velocity is double UW2 & terminal velocity estimate

### ISSUE THREAD

**Issue by bknight1** [underworldcode/underworld3-archive#85]
Hi team,

I've written a stokes sinker example comparing UW2 and UW3 using the stokes sinker example from UW2.  However the sinker velocity in UW3 is double the stokes terminal velocity estimation (and UW2 velocity).  This can be resolved by doubling the viscosity or halving the density of the materials in UW3, or doubling the time of the UW3 model. I've attached the script, which should work using the ConstitutiveModelUpdates branch.

Cheers

[UWComp_StokesSinker.py.txt](https://github.com/underworldcode/underworld3/files/9439213/UWComp_StokesSinker.py.txt)

**Comment by bknight1** [comment]
Stokes sinker Linear version now works after 7298885df19d9f9dd001ba200f5e774485b72661 

However I'm unable to get a non-linear version to converge at a higher element res (currently works at 20x20). The error message is: `Nonlinear Stokes_1_ solve did not converge due to DIVERGED_LINEAR_SOLVE`. 

I've attached an updated script with the code.

Cheers


[UWComp_StokesSinker-NL.py.txt](https://github.com/underworldcode/underworld3/files/9442163/UWComp_StokesSinker-NL.py.txt)

**Comment by knepley** [comment]
First, I would make sure that the Jacobian is correct. You can use `-snes_test_jacobian` and `-snes_test_jacobian_view` to see if it is right.

**Comment by bknight1** [comment]
Thanks @knepley for the advice, the Jacobian was set up fine, I had messed up some scaling in the script. I've managed to create a working version which I've uploaded to the repo f74e022a4d84117a78be906592f3b6daf9aeab9c
