### ISSUE TITLE
DIVERGED_LINE_SEARCH caused by BC (?)

### ISSUE THREAD

**Issue by bknight1** [underworldcode/underworld3-archive#97]
I'm trying out the basic stokes sinker problem and running into 'DIVERGED_LINE_SEARCH' when using a free slip boundary and unstructured regular mesh (regular=True). No slip BC solves fine for both mesh types. The non-regular mesh (regular=False) returns 'DIVERGED_LINE_SEARCH' in the stokes loop. 

```
# No slip
sol_vel = sympy.Matrix([0, 0])

stokes.add_dirichlet_bc(sol_vel, ["Top", "Bottom"], [0, 1])  # top/bottom: components, function, markers
stokes.add_dirichlet_bc(sol_vel, ["Left", "Right"], [0, 1])  # left/right: components, function, markers

# free slip
stokes.add_dirichlet_bc((0.0), "Left", (0,))
stokes.add_dirichlet_bc((0.0), "Right", (0,))
stokes.add_dirichlet_bc((0.0), "Bottom", (1,))
stokes.add_dirichlet_bc((0.0), "Top", (1,))

```

This can be recreated using the [stokes sinker example](https://github.com/underworldcode/underworld3/blob/98e346b7f35d88f9f1bb1275408464b4dc1a00d7/Jupyterbook/Notebooks/Examples-StokesFlow/Ex_Stokes_Sinker.py), and switching the regular parameter to 'True' and adding the free slip conditions.

This may also be where we're running into issues with other models (e.g. the notch/VP problem).

Cheers

**Comment by bknight1** [comment]
> I've been looking into it a bit further, it seems like there were two issues with the code I was trying to run. The BC weren't implemented correctly, with the following working:
> ```
> stokes.add_dirichlet_bc(sympy.Matrix([0, 0]), "Left", (0,))
> stokes.add_dirichlet_bc(sympy.Matrix([0, 0]), "Right", (0,))
> stokes.add_dirichlet_bc(sympy.Matrix([0, 0]), "Top", (1,))
> stokes.add_dirichlet_bc(sympy.Matrix([0, 0]), "Bottom", (1,))
> ```
> 
> I also had to change the material swarm variable to use a non-continuous proxy variable:
> 
> `material = uw.swarm.IndexSwarmVariable("M", swarm, indices=2, proxy_degree=1, proxy_continuous=False)`
> 
> Using 'proxy_continuous=True' results in a DIVERGED_LINE_SEARCH for an irregular (regular=False) and regular (regular=True) mesh.

Actually that didn't work, but reducing the viscosity contrast between the sphere and background did help... 'DIVERGED_LINE_SEARCH' seems to occur when the viscosity contrast is >2e3 when using the free slip BC. With no slip, the contrast can be much larger.

**Comment by bknight1** [comment]
Still getting this issue when testing the block sinker example/benchmark from [Gerya et al., 2003](http://jupiter.ethz.ch/~tgerya/reprints/2003_PEPI_method.pdf), fig 5. No slip boundaries are okay but free-slip is generating a divided_line_search with viscosity contrasts >=100.

**Comment by knepley** [comment]
If all your boundaries are free slip, isn't there a rotational null mode?

**Comment by lmoresi** [comment]
Cartesian box, I think.

Sent from my iPhone

On 13 Dec 2022, at 5:47 pm, Matthew Knepley ***@***.***> wrote:

﻿

If all your boundaries are free slip, isn't there a rotational null mode?

**Comment by bknight1** [comment]
Yes it's a cartesian box, none of the box setups work
