### ISSUE TITLE
AdvectionDiffusion estimate dt()

### ISSUE THREAD

**Issue by julesghub** [underworldcode/underworld3-archive#98]
Add an estimate_dt() functionality on the AdvectionDiffusion solver that take diffusion processes into account.

Think about a general design pattern of these timestepping mechanisms.

**Comment by bknight1** [comment]
My [NL diffusion example version](https://github.com/underworldcode/underworld3/blob/main/Jupyterbook/Notebooks/Examples-PoissonEquation/Ex_DiffusionSLCN_Cartesian-NL.py) took into account changes in the NL diffusivity over time:

```
k = uw.discretisation.MeshVariable("k", mesh, 1, degree=1)

k_model = uw.systems.Projection(mesh, k)
k_model.uw_function = adv_diff.constitutive_model.Parameters.diffusivity
k_model.smoothing = 1.0e-3

def estimate_dt():
    k_model.uw_function = adv_diff.constitutive_model.Parameters.diffusivity
    k_model.solve(_force_setup=True)

    with mesh.access(k):
        ### estimate the timestep based on diffusion only
        dt = (
            mesh.get_min_radius() ** 2 / k.data[:, 0].max()
        )  ### dt = length squared / diffusivity

    print(f"dt: {dt}")

    return dt
```

**Comment by lmoresi** [comment]
Can we close this @bknight1 ?

**Comment by bknight1** [comment]
Yeah should be all good
